# Generated by Django 5.1.2 on 2024-12-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_campaign_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
