# Generated by Django 5.1.4 on 2024-12-15 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_simplify_contact_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_owner',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='actual_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budgeted_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expected_response',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='numbers_sent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('social', 'Social Media'), ('mail', 'Direct Mail'), ('other', 'Other')], default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
