# Generated by Django 5.1.2 on 2024-12-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact_company_contact_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='position',
        ),
    ]
