# Generated by Django 5.1.2 on 2025-01-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='core.contact'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='lead_campaigns', to='core.contact'),
        ),
    ]
