# Generated by Django 5.1.2 on 2025-01-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_campaign_actual_revenue_alter_opportunity_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('prospecting', 'Prospecting'), ('qualification', 'Qualification'), ('needs-analysis', 'Needs Analysis'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed-won', 'Closed Won'), ('closed-lost', 'Closed Lost')], max_length=50),
        ),
    ]
